### ISSUE TITLE
The authorization header is malformed; the region 'eu-west-1' is wrong; expecting 'us-east-1'

### ISSUE THREAD

**Issue by ljanyst** [owncloud/files_external_s3#163]
Apparently this is some sort of a conflict with `files_primary_s3`. It picks up the the aws sdk from there. Please note, that if I have not external S3 storage mounted, this warning does not appear.

```
{"reqId":"","level":3,"time":"2019-05-07T22:01:38+00:00","remoteAddr":"","user":"ljanyst","app":"files_external","method":"GET","url":"\/oc\/apps\/files_external\/userstorages\/9?testOnly=true","message":"Exception: {\"Exception\":\"Aws\\\\S3\\\\Exception\\\\S3Exception\",\"Message\":\"Error executing \\\"ListBuckets\\\" on \\\"https:\\\/\\\/s3.amazonaws.com\\\/\\\"; AWS HTTP error: Client error response [url] https:\\\/\\\/s3.amazonaws.com\\\/ [status code] 400 [reason phrase] Bad Request AuthorizationHeaderMalformed (client): The authorization header is malformed; the region 'eu-west-1' is wrong; expecting 'us-east-1' - <?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<Error><Code>AuthorizationHeaderMalformed<\\\/Code><Message>The authorization header is malformed; the region 'eu-west-1' is wrong; expecting 'us-east-1'<\\\/Message><Region>us-east-1<\\\/Region><RequestId><\\\/RequestId><HostId><\\\/HostId><\\\/Error>\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/aws\\\/aws-sdk-php\\\/src\\\/WrappedHttpHandler.php(100): Aws\\\\WrappedHttpHandler->parseError(Array, Object(GuzzleHttp\\\\Psr7\\\\Request), Object(Aws\\\\Command), Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(203): Aws\\\\WrappedHttpHandler->Aws\\\\{closure}(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(174): GuzzleHttp\\\\Promise\\\\Promise::callHandler(2, Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/RejectedPromise.php(40): GuzzleHttp\\\\Promise\\\\Promise::GuzzleHttp\\\\Promise\\\\{closure}(Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/TaskQueue.php(47): GuzzleHttp\\\\Promise\\\\RejectedPromise::GuzzleHttp\\\\Promise\\\\{closure}()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(246): GuzzleHttp\\\\Promise\\\\TaskQueue->run(true)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(223): GuzzleHttp\\\\Promise\\\\Promise->invokeWaitFn()\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(267): GuzzleHttp\\\\Promise\\\\Promise->waitIfPending()\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(225): GuzzleHttp\\\\Promise\\\\Promise->invokeWaitList()\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(62): GuzzleHttp\\\\Promise\\\\Promise->waitIfPending()\\n#10 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/aws\\\/aws-sdk-php\\\/src\\\/AwsClientTrait.php(58): GuzzleHttp\\\\Promise\\\\Promise->wait()\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/aws\\\/aws-sdk-php\\\/src\\\/AwsClientTrait.php(77): Aws\\\\AwsClient->execute(Object(Aws\\\\Command))\\n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external_s3\\\/lib\\\/Storage\\\/AmazonS3.php(545): Aws\\\\AwsClient->__call('listBuckets', Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/External\\\/LegacyUtil.php(205): OCA\\\\FilesExternalS3\\\\Storage\\\\AmazonS3->test(false, 'true')\\n#14 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(254): OC\\\\Files\\\\External\\\\LegacyUtil::getBackendStatus('OCA\\\\\\\\FilesExtern...', Array, false, 'true')\\n#15 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(303): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OC\\\\Files\\\\External\\\\StorageConfig), 'true')\\n#16 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/UserStoragesController.php(105): OCA\\\\Files_External\\\\Controller\\\\StoragesController->show('9', 'true')\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OCA\\\\Files_External\\\\Controller\\\\UserStoragesController->show('9', 'true')\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\UserStoragesController), 'show')\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\UserStoragesController), 'show')\\n#20 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Files_Exter...', 'show', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#21 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#22 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#23 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#24 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/aws\\\/aws-sdk-php\\\/src\\\/WrappedHttpHandler.php\",\"Line\":191}"}
```

**Comment by tedyu** [comment]
How did you solve this issue ?

thanks

**Comment by ljanyst** [comment]
I haven't. I think they need to unify the two plugins to fix this. Or introduce a dependency management system, so that both plugins can use the same s3 framework.

**Comment by Vieufoux** [comment]
Hi @PVince81 ,I also met the same error. I can use us-east-1 bucket successfully, but when I want to use cn-north-1 bucket as external storage, i got the error below from ownCloud log (data/owncloud.log):
 The authorization header is malformed; the region 'cn-north-1' is wrong; expecting 'us-east-1'

**Comment by PVince81** [comment]
might be fixed through https://github.com/owncloud/files_external_s3/pull/232

**Comment by ljanyst** [comment]
Seems unlikely, but I will have a look in the evening.

**Comment by PVince81** [comment]
> It does indeed work, but does not show any keys that would end up in subfolders...

likely related to https://github.com/owncloud/files_external_s3/issues/7

**Comment by ljanyst** [comment]
Yes, it seems like it's exactly that.

Thanks for fixing this one! :)

**Comment by ljanyst** [comment]
It seems like it fixes the issue only for some buckets. For some others with exactly the same access policy I still get:

```{"reqId":"--","level":3,"time":"2019-09-15T22:34:17+00:00","remoteAddr":"--","user":"--","app":"files_external","method":"GET","url":"\/oc\/apps\/files_external\/userstorages\/5?testOnly=true","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Creation of bucket failed. Error executing \\\"CreateBucket\\\" on \\\"https:\\\/\\\/---\\\/\\\"; AWS HTTP error: Client error response [url] https:\\\/\\\/---\\\/ [status code] 400 [reason phrase] Bad Request AuthorizationHeaderMalformed (client): The authorization header is malformed; the region 'eu-west-1' is wrong; expecting 'us-east-1' - <?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<Error><Code>AuthorizationHeaderMalformed<\\\/Code><Message>The authorization header is malformed; the region 'eu-west-1' is wrong; expecting 'us-east-1'<\\\/Message><Region>us-east-1<\\\/Region><RequestId>---<\\\/RequestId><HostId>---<\\\/HostId><\\\/Error>\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external_s3\\\/lib\\\/Storage\\\/AmazonS3.php(534): OCA\\\\FilesExternalS3\\\\Storage\\\\AmazonS3->getConnection()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/External\\\/LegacyUtil.php(205): OCA\\\\FilesExternalS3\\\\Storage\\\\AmazonS3->test(false, 'true')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(254): OC\\\\Files\\\\External\\\\LegacyUtil::getBackendStatus('OCA\\\\\\\\FilesExtern...', Array, false, 'true')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(303): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OC\\\\Files\\\\External\\\\StorageConfig), 'true')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/UserStoragesController.php(105): OCA\\\\Files_External\\\\Controller\\\\StoragesController->show('5', 'true')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OCA\\\\Files_External\\\\Controller\\\\UserStoragesController->show('5', 'true')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\UserStoragesController), 'show')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\UserStoragesController), 'show')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Files_Exter...', 'show', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external_s3\\\/lib\\\/Storage\\\/AmazonS3.php\",\"Line\":619}"}

```
