### ISSUE TITLE
Unable to delete S3 folder

### ISSUE THREAD

**Issue by alfeltrin** [owncloud/files_external_s3#393]
When i try to delete a folder i receive this error.
{"reqId":"49qiGyoRN7n9FtQtyzzS","level":0,"time":"2020-04-21T10:00:03+00:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"user","app":"webdav","method":"DELETE","url":"\/remote.php\/dav\/files\/user\/S3\/123","message":"Exception: HTTP\/1.1 403 Forbidden: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Forbidden\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(183): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->delete()\\n#1 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(295): Sabre\\\\DAV\\\\Tree->delete('files\\\/user\\\/S3\\\/1...')\\n#2 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(474): Sabre\\\\DAV\\\\Server->emit('method:DELETE', Array)\\n#4 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(251): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/dav\\\/lib\\\/Server.php(329): Sabre\\\\DAV\\\\Server->start()\\n#6 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#7 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/remote.php(165): require_once('\\\/opt\\\/bitnami\\\/ap...')\\n#8 {main}\",\"File\":\"\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php\",\"Line\":345}"}

I've installed the latest verion both of Owncloud and than S3 external storage app; the file deletion works fine, the problem appen only with the folders.
I've also tryed to delete the folder from AWS cli and the folder are correctly been removed, so i don't think it's an aws permission problem.

**Comment by Linda-chan** [comment]
Same issue here using DigitalOcean spaces as S3 storage. Files are deleted normally but OC can't delete folders. OC core and S3 app are fresh.

// Also had really hard time figuring out how to stop all these «Transaction timeout» errors flooding log file.

**Comment by coast-ch** [comment]
same here

**Comment by garafutdinovash** [comment]
the problem is still relevant, when will it be solved?

**Comment by Jasonnor** [comment]
Same as above, is there any progress? Thanks.

**Comment by emolvera** [comment]
I have this issue as well. I get the error "Error deleting file" when trying to delete a folder in S3

**Comment by jayennis22** [comment]
Me too.  This is still happening in 10.9.1.  Verified that I can manually delete these folders using the same IAM user.

**Comment by ivnmad** [comment]
I installed the ownCloud extension today and it still included the issue described here.
It looks as if the fix never made it to a new S3 storage extension version on Marketplace.
I manually changed the file in my installation and it fixes the problem nicely.
