### ISSUE TITLE
[QA] cannot delete folders; rename duplicates folders

### ISSUE THREAD

**Issue by jnweiger** [owncloud/files_external_s3#973]
Seen while testing files_external_s3-2.0.0-rc.1 with owncloud core 10.11.0-alpha.2

* Configure an external storage using a scality s3 server
![image](https://user-images.githubusercontent.com/1108546/185680251-4af90f99-8b19-4b49-8115-63bf2fe89500.png)

----

Using the Web UI:
* create a subfolder logs in /s3-bucket
* add a file into /s3-bucket/logs/
* rename the subfolder 'logs' to 'renamed' - the rename seems to succeed. The contens is there.
* shift reload the web UI. The 'logs' folder appears next to 'renamed'. BAD.
* contents is in both folders. BAD.
* no error messages are logged. BAD.
----
* try to delete the folder 'logs' in '/s3-bucket'. An error appears: 'Error deleting file "logs"'. BAD
```
{"reqId":"Yv-6mU6yr1YqLYqw4FyyygAAAAI","level":0,"time":"2022-08-19T21:03:21+00:00","remoteAddr":"84.180.179.44","user":"admin","app":"OC\\User\\Session::validateToken","method":"DELETE","url":"\/remote.php\/dav\/files\/admin\/s3-bucket\/logs","message":"token abd7868467920b695200b4f4b32583532a8c97e4d55d57c35e01528a886993bc4aacf819f3cf5d3ec7161d352ad6989ded1b48bdbaaa576f6e8bfc5dd7e137b6 with token id 1 found, validating"}
{"reqId":"Yv-6mU6yr1YqLYqw4FyyygAAAAI","level":0,"time":"2022-08-19T21:03:21+00:00","remoteAddr":"84.180.179.44","user":"admin","app":"webdav","method":"DELETE","url":"\/remote.php\/dav\/files\/admin\/s3-bucket\/logs","message":"Exception: HTTP\/1.1 403 Forbidden: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Forbidden\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->delete()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(281): Sabre\\\\DAV\\\\Tree->delete()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpDelete()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(349): Sabre\\\\DAV\\\\Server->start()\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php\",\"Line\":350}"}

```

Workaround:
* use `s3cmd del --recursive ...` to really remove folders.

It makes no difference, if te folder was empty.
Files can be deleted without problems, though.

**Comment by jnweiger** [comment]
The folder delete issue can be trivially reproduced:
.
* in an external s3 mount, create a new (empty) folder.
* try delete. It fails.
